/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Anton', 'sans-serif'],
        grotesk: ['Anton', 'sans-serif'],
        sans: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        serif: ['"Instrument Serif"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', '"SF Mono"', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        background: '#f4f2ee',
        graphite: '#f4f2ee',
        surface:   '#ffffff',
        'surface-2': '#eceae5',
        'surface-3': '#e5e2db',
        bone:  '#0d0d0d',
        muted: '#666666',
        steel: '#aaaaaa',
        vital: '#c8102e',
        oxygen: '#1a5276',
        'bio-green': '#00c8a0',
        blueprint:   '#1a3a5c',
        ink:   '#0d0d0d',
        paper: '#f4f2ee',
      },
      maxWidth: { container: '1440px' },
      letterSpacing: {
        tightest: '-0.04em',
        display:  '-0.03em',
        ui:       '0.01em',
        caps:     '0.18em',
        widecaps: '0.30em',
      },
      keyframes: {
        'rule-draw': { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        'comp-rise': { from: { transform: 'translateY(105%)' }, to: { transform: 'translateY(0)' } },
        'comp-in':   { from: { opacity: '0' }, to: { opacity: '1' } },
        'flap-in':   { '0%': { transform: 'rotateX(90deg)', opacity: '0' }, '100%': { transform: 'rotateX(0deg)', opacity: '1' } },
        'stamp-drop': {
          '0%':   { transform: 'translateY(-10px) scale(1.08) rotate(-2deg)', opacity: '0' },
          '60%':  { transform: 'translateY(1px)  scale(0.96) rotate(-2deg)', opacity: '1' },
          '100%': { transform: 'translateY(0px)  scale(1)    rotate(-2deg)', opacity: '1' },
        },
        'ink-spread': {
          from: { clipPath: 'inset(0 100% 0 0)' },
          to:   { clipPath: 'inset(0 0% 0 0)' },
        },
        'pulse-slow': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.55' } },
        'breathe':    { '0%, 100%': { opacity: '0.3' }, '50%': { opacity: '0.75' } },
        'ekg':        { '0%': { strokeDashoffset: '2000' }, '100%': { strokeDashoffset: '0' } },
      },
      animation: {
        'rule-draw':  'rule-draw 0.55s cubic-bezier(0.4,0,0.2,1) both',
        'comp-rise':  'comp-rise 0.65s cubic-bezier(0.16,1,0.3,1) both',
        'comp-in':    'comp-in 0.4s ease both',
        'flap-in':    'flap-in 0.14s ease-out both',
        'stamp-drop': 'stamp-drop 0.32s cubic-bezier(0.4,0,0.2,1) both',
        'ink-spread': 'ink-spread 0.9s cubic-bezier(0.4,0,0.2,1) both',
        'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
        'breathe':    'breathe 4s ease-in-out infinite',
        'ekg':        'ekg 6s linear infinite',
      },
    },
  },
  plugins: [],
};
